/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/AppContainer/index.vue')['default']
    BindMobile: typeof import('./src/components/BindMobile/index.vue')['default']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoadingAnnulus: typeof import('./src/components/Loading/static/loading-annulus.vue')['default']
    LoadingAtom: typeof import('./src/components/Loading/static/loading-atom.vue')['default']
    LoadingBounce: typeof import('./src/components/Loading/static/loading-bounce.vue')['default']
    LoadingCircle: typeof import('./src/components/Loading/static/loading-circle.vue')['default']
    LoadingEqual: typeof import('./src/components/Loading/static/loading-equal.vue')['default']
    LoadingEyes: typeof import('./src/components/Loading/static/loading-eyes.vue')['default']
    LoadingGear: typeof import('./src/components/Loading/static/loading-gear.vue')['default']
    LoadingLove: typeof import('./src/components/Loading/static/loading-love.vue')['default']
    LoadingPulse: typeof import('./src/components/Loading/static/loading-pulse.vue')['default']
    LoadingRadar: typeof import('./src/components/Loading/static/loading-radar.vue')['default']
    LoadingSun: typeof import('./src/components/Loading/static/loading-sun.vue')['default']
    LoadingSurround: typeof import('./src/components/Loading/static/loading-surround.vue')['default']
    LoadingSword: typeof import('./src/components/Loading/static/loading-sword.vue')['default']
    LoadingWobble: typeof import('./src/components/Loading/static/loading-wobble.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutEmpty: typeof import('nutui-uniapp/components/empty/empty.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutRate: typeof import('nutui-uniapp/components/rate/rate.vue')['default']
    NutStep: typeof import('nutui-uniapp/components/step/step.vue')['default']
    NutSteps: typeof import('nutui-uniapp/components/steps/steps.vue')['default']
    NutTag: typeof import('nutui-uniapp/components/tag/tag.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    PageList: typeof import('./src/components/PageList/index.vue')['default']
  }
}
