/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/AppContainer/index.vue')['default']
    BindMobile: typeof import('./src/components/BindMobile/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoadingAnnulus: typeof import('./src/components/Loading/comps/loading-annulus.vue')['default']
    LoadingAtom: typeof import('./src/components/Loading/comps/loading-atom.vue')['default']
    LoadingBounce: typeof import('./src/components/Loading/comps/loading-bounce.vue')['default']
    LoadingCircle: typeof import('./src/components/Loading/comps/loading-circle.vue')['default']
    LoadingEqual: typeof import('./src/components/Loading/comps/loading-equal.vue')['default']
    LoadingEyes: typeof import('./src/components/Loading/comps/loading-eyes.vue')['default']
    LoadingGear: typeof import('./src/components/Loading/comps/loading-gear.vue')['default']
    LoadingLove: typeof import('./src/components/Loading/comps/loading-love.vue')['default']
    LoadingPulse: typeof import('./src/components/Loading/comps/loading-pulse.vue')['default']
    LoadingRadar: typeof import('./src/components/Loading/comps/loading-radar.vue')['default']
    LoadingSun: typeof import('./src/components/Loading/comps/loading-sun.vue')['default']
    LoadingSurround: typeof import('./src/components/Loading/comps/loading-surround.vue')['default']
    LoadingSword: typeof import('./src/components/Loading/comps/loading-sword.vue')['default']
    LoadingWobble: typeof import('./src/components/Loading/comps/loading-wobble.vue')['default']
    MpHtml: typeof import('./src/components/mp-html/mp-html.vue')['default']
    Node: typeof import('./src/components/mp-html/node/node.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutDivider: typeof import('nutui-uniapp/components/divider/divider.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutTag: typeof import('nutui-uniapp/components/tag/tag.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    Recharge: typeof import('./src/components/Recharge/index.vue')['default']
    WeappTailwindcss: typeof import('./src/components/WeappTailwindcss.vue')['default']
  }
}
